# Generated by Django 5.1.7 on 2025-03-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPortfolioApplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=200)),
                ('skills', models.TextField()),
            ],
        ),
    ]
