# Generated by Django 5.1.7 on 2025-03-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TPortfolioApplication', '0002_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='skills',
        ),
        migrations.AddField(
            model_name='teammember',
            name='skills',
            field=models.ManyToManyField(to='TPortfolioApplication.skill'),
        ),
    ]
